### NumPy

- NumPy stands for Numerical Python
- A Python library that provides support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays

#### Why NumPy?

- NumPy aims to provide an array object that is up to 50x faster than traditional Python lists
- The array object in NumPy is called ndarray; it provides a lot of supporting functions that make working with ndarray very easy
- NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently which is the main reason why the former is faster than the latter


In [1]:
## Installing numpy
# pip install numpy

#### Creating ndarrays

In [2]:
## Creating an array of integers using array() method

import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [3]:
print(type(arr))


<class 'numpy.ndarray'>


To create an ndarray, we can pass a list, tuple or any array-like object into the array() method, and it will be converted into an ndarray

In [4]:
## Creating array of zeros and ones

arr1 = np.zeros((2,3))
print("Array of zeros: \n", arr1)

arr2 = np.ones((1,5))
print("Array of ones: \n", arr2)



Array of zeros: 
 [[0. 0. 0.]
 [0. 0. 0.]]
Array of ones: 
 [[1. 1. 1. 1. 1.]]


In [5]:
## Creating array using arange()
## arange() is an array creation routine based on numerical ranges
## It creates an instance of ndarray with evenly spaced values and returns the reference to it

arr = np.arange(4)
print(arr)


[0 1 2 3]


numpy.arange([start, ]stop, [step, ], dtype=None) -> numpy.ndarray

The first three parameters determine the range of the values, while the fourth specifies the type of the elements:

- start is the number (integer or decimal) that defines the first value in the array
- stop is the number that defines the end of the array and isn’t included in the array
- step is the number that defines the spacing (difference) between each two consecutive values in the array and defaults to 1
- dtype is the type of the elements of the output array and defaults to None

In [6]:
arr = np.arange(1, 15, 3, dtype=np.int32)
print(arr)



[ 1  4  7 10 13]


#### Dimensions in Arrays
A dimension in arrays is one level of array depth (nested arrays)

`Nested array: arrays that have arrays as their elements`

In [7]:
## 0-D arrays, or Scalars, are the elements in an array 
## Each value in an array is a 0-D array

a = np.array(23)
print(a)


23


In [8]:
## An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array
## The most common and basic arrays

b = np.array([13,26,39])
print(b)


[13 26 39]


In [9]:
## An array that has 1-D arrays as its elements is called a 2-D array
## Often used to represent matrix or 2nd order tensors

c = np.array([[1, 2, 3], [4, 5, 6]])
print(c)


[[1 2 3]
 [4 5 6]]


In [10]:
## An array that has 2-D arrays (matrices) as its elements is called 3-D array
## These are often used to represent a 3rd order tensor

d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(d)


[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [11]:
## Checking dimensions
## ndim attribute returns an integer that indicates how many dimensions the array has

print(c.ndim)
print(a.ndim)



2
0


In [12]:
## Creating higher dimensional arrays by defining the number of dimensions by using the ndmin argument

e = np.array([1, 2, 3, 4], ndmin=5)
print(e)
print("Number of dimensons: ", e.ndim)


[[[[[1 2 3 4]]]]]
Number of dimensons:  5


In this array the innermost dimension (5th dim) has 4 elements, the 4th dim has 1 element that is the vector, the 3rd dim has 1 element that is the matrix with the vector, the 2nd dim has 1 element that is 3D array and 1st dim has 1 element that is a 4D array.

#### Array Indexing

- Array indexing means accessing an array element by referring to its index number
- The indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1, etc

In [13]:
arr = np.array([23,67,9,84])
print(arr)


[23 67  9 84]


In [14]:
## Accessing the second element of the array
print(arr[1])


67


In [15]:
## Accessing the 4th element
print(arr[3])


84


In [16]:
## Getting third and fourth elements from the above array and adding them
print(arr[2] + arr[3])


93


In [17]:
## To access elements from 2-D arrays we can use comma separated integers
## representing the dimension and the index of the element

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('2nd element on 1st dim: ', arr[0, 1])


2nd element on 1st dim:  2


In [18]:
print('5th element on 2nd dim: ', arr[1, 4])


5th element on 2nd dim:  10


In [19]:
## To access elements from 3-D arrays we can use comma separated integers 
## representing the dimensions and the index of the element

## Accessing the third element of the second array of the first array
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr[0, 1, 2])

6


##### Explanation of above example

`arr[0, 1, 2]` prints the value `6`.

And this is why:

The first number represents the first dimension, which contains two arrays: `[[1, 2, 3], [4, 5, 6]]` and `[[7, 8, 9], [10, 11, 12]]`

Since we selected 0, we are left with the first array: `[[1, 2, 3], [4, 5, 6]]`

The second number represents the second dimension, which also contains two arrays: `[1, 2, 3]` and `[4, 5, 6]`

Since we selected 1, we are left with the second array: `[4, 5, 6]`

The third number represents the third dimension, which contains three values: 4, 5, 6

Since we selected 2, we end up with the third value: 6

In [20]:
## Negative indexing is used to access an array from the end

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('Last element from 2nd dim: ', arr[1, -1])


Last element from 2nd dim:  10


#### Array Slicing

- Slicing in python means taking elements from one given index to another given index
- We may pass slice instead of index like this: `[start:end]`
- We can also define the step: `[start:end:step]`
- If we don't pass start it's considered 0
- If we don't pass end it considers length of array in that dimension
- If we don't pass step it's considered 1

In [21]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5])


[2 3 4 5]


The result includes the start index, but excludes the end index

In [22]:
## Slicing elements from index 4 to the end of the array
print(arr[4:])


[5 6 7]


In [23]:
## Slicing elements from the beginning to index 4 (not included)
print(arr[:4])


[1 2 3 4]


In [24]:
## Negative Slicing - use the minus operator to refer to an index from the end

## Slicing from the index 3 from the end to index 1 from the end
print(arr[-3:-1])


[5 6]


In [25]:
## Using the step value to determine the step of the slicing

## Returning every other element from index 1 to index 5
print(arr[1:5:2])


[2 4]


In [26]:
## Returning every other element from the entire array
print(arr[::2])


[1 3 5 7]


In [27]:
## Slicing 2D arrays
## From the second element, slicing elements from index 1 to index 4 (not included)

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[1, 1:4])



[7 8 9]


In [28]:
## Returning index 2 from both elements
print(arr[0:2, 2])


[3 8]


In [29]:
# ## Slicing index 1 to index 4 from both elements\
print(arr[0:2, 1:4])


[[2 3 4]
 [7 8 9]]


#### NumPy Data Types

- i - integer
- b - boolean
- u - unsigned integer
- f - float
- c - complex float
- m - timedelta
- M - datetime
- O - object
- S - string
- U - unicode string
- V - fixed chunk of memory for other type ( void )

##### Checking the Data Type of an Array
The NumPy array object has a property called dtype that returns the data type of the array

In [30]:
arr = np.array([1, 2, 3, 4])
print(arr.dtype)


int32


In [31]:
arr = np.array(['apple', 'orange', 'cherry']) # object data type <U6
print(arr.dtype)


<U6


In [32]:
## Creating Arrays With a Defined Data Type
## The array() function can take an optional argument "dtype" 
## that allows us to define the expected data type of the array elements\

## Creating an array with data type string
arr = np.array([1, 2, 3, 4], dtype='S')
print(arr)
print(arr.dtype)



[b'1' b'2' b'3' b'4']
|S1


For i, u, f, S and U we can define size as well

In [33]:
## Creating an array with data type 4 bytes integer

arr = np.array([1, 2, 3, 4], dtype='i4')
print(arr)
print(arr.dtype)



[1 2 3 4]
int32


In [34]:
## Converting Data Type on Existing Arrays
## Make a copy of the array with the astype() method
## The astype() function creates a copy of the array, and allows you to specify the data type as a parameter

arr = np.array([1.1, 2.1, 3.1])
print(arr)
print(arr.dtype)



[1.1 2.1 3.1]
float64


In [35]:
newarr = arr.astype('i')
print(newarr)
print(newarr.dtype)



[1 2 3]
int32


In [36]:
## Alternative way

newarr = arr.astype(int)
print(newarr)
print(newarr.dtype)



[1 2 3]
int32


#### NumPy Array Copy vs View

- The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array

- The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy

- The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view

In [37]:
## Making a copy, changing the original array, and displaying both arrays

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [38]:
## Making a view, changing the original array, and displaying both arrays

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [39]:
## Making a view, changing the view, and displaying both arrays

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
x[0] = 31

print(arr)
print(x)

[31  2  3  4  5]
[31  2  3  4  5]


#### Shape of an Array

- The shape of an array is the number of elements in each dimension
- NumPy arrays have an attribute called shape that returns a tuple with each index having the number of corresponding elements

In [40]:
## Printing the shape of a 2-D array

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr.shape)



(2, 4)


The example above returns (2, 4), which means that the array has 2 dimensions, and each dimension has 4 elements.

In [41]:
arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)
print('shape of array :', arr.shape)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


Integers at every index tells about the number of elements the corresponding dimension has.

In the above case at index-4 we have value 4, so we can say that 5th ( 4 + 1 th) dimension has 4 elements.

#### Reshaping Arrays

- Reshaping means changing the shape of an array
- By reshaping we can add or remove dimensions or change number of elements in each dimension

In [42]:
## Converting a 1-D array with 12 elements into a 2-D array
## such that the outermost dimension will have 4 arrays, each with 3 elements

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4, 3)
print(newarr)



[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [43]:
## Converting a 1-D array with 12 elements into a 3-D array
## such that the outermost dimension will have 2 arrays that contains 3 arrays, each with 2 elements

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(2, 3, 2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


Note: We can reshape an array into any shape as long as the elements required for reshaping are equal in both shapes

For eg, we can reshape an 8 elements 1D array into 4 elements in 2 rows 2D array but we cannot reshape it into a 3 elements 3 rows 2D array as that would require 3x3 = 9 elements

In [44]:
## Flattening array - converting a multidimensional array into a 1D array

arr = np.array([[1, 2, 3], [4, 5, 6]])
newarr = arr.reshape(-1)
print(newarr)


[1 2 3 4 5 6]


We can also use flatten() - transforms an n-dimensional array into a one-dimensional array

In [84]:
arr.flatten()

array([ 2,  4,  6, 10, 11, 12])

ravel() - works in the same way as flatten() but returns the reference of the original array. Much faster than flatten() as it doesn't occupy extra memory

In [85]:
arr.ravel()

array([ 2,  4,  6, 10, 11, 12])

#### Sorting Arrays

Arranging elements of a NumPy ndarray object in an ordered sequence is achieved by a function called sort() 

In [45]:
arr = np.array([3, 2, 0, 1])
print(np.sort(arr))


[0 1 2 3]


This method returns a copy of the array, leaving the original array unchanged

In [46]:
## Sorting the array alphabetically

arr = np.array(['banana', 'cherry', 'apple'])
print(np.sort(arr))


['apple' 'banana' 'cherry']


In [47]:
## Using the sort() method on a 2-D array will render both arrays sorted

arr = np.array([[3, 2, 4], [5, 0, 1]])
print(np.sort(arr))


[[2 3 4]
 [0 1 5]]


#### Searching Arrays

You can search an array for a certain value, and return the indexes that get a match using the where() method

In [48]:
## Finding the indexes where the value is 4

arr = np.array([1, 2, 3, 4, 5, 4, 4])
x = np.where(arr == 4)
print(x)



(array([3, 5, 6], dtype=int64),)


In [49]:
## Finding the indexes where the values are even

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
x = np.where(arr%2 == 0)
print(x)



(array([1, 3, 5, 7], dtype=int64),)


#### Joining NumPy Arrays 

- Joining means putting contents of two or more arrays in a single array
- In SQL we join tables based on a key, whereas in NumPy we join arrays by axes
- We pass a sequence of arrays that we want to join to the concatenate() function, along with the axis; if axis is not explicitly passed, it is taken as 0.


In [50]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))
print(arr)



[1 2 3 4 5 6]


In [51]:
## Joining two 2-D arrays along rows (axis=1)

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)
print(arr)



[[1 2 5 6]
 [3 4 7 8]]


#### Joining Arrays Using Stack Functions

- Stacking is same as concatenation, the only difference is that stacking is done along a new axis
- We can concatenate two 1-D arrays along the second axis which would result in putting them one over the other, ie. stacking
- We pass a sequence of arrays that we want to join to the stack() method along with the axis; if axis is not explicitly passed it is taken as 0

In [52]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)
print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [53]:
## Stacking Along Rows - hstack()

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


In [54]:
## Stacking Along Columns - vstack()

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))
print(arr)



[[1 2 3]
 [4 5 6]]


#### Splitting NumPy Arrays

- Splitting is reverse operation of Joining, that is breaks one array into multiple arrays
- We use array_split() for splitting arrays, we pass it the array we want to split and the number of splits

In [55]:
## Splitting the array in 3 parts

arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 3)
print(newarr)



[array([1, 2]), array([3, 4]), array([5, 6])]


The return value is an array containing three arrays

In [56]:
## If the array has less elements than required, it will adjust from the end accordingly
## Splitting the array in 4 parts

arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 4)
print(newarr)



[array([1, 2]), array([3, 4]), array([5]), array([6])]


We also have the method split() available but it will not adjust the elements when elements are less in source array for splitting like in example above, array_split() worked properly but split() would fail.

In [57]:
## The return value of the array_split() method is an array containing each of the split as an array
## If you split an array into 3 arrays, you can access them from the result just like any array element

arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 3)

print(newarr[0])
print(newarr[1])
print(newarr[2])



[1 2]
[3 4]
[5 6]


In [58]:
## Splitting a 2-D array into three 2-D arrays

arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
newarr = np.array_split(arr, 3)
print(newarr)



[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


#### NumPy Arithmetic Operations

Input arrays for performing arithmetic operations such as add(), subtract(), multiply(), and divide() must be either of the same shape or should conform to array broadcasting rules

In [59]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[7,8,9],[10,11,12]])

In [60]:
## Adding the two arrays
print(np.add(arr1,arr2))


[[ 8 10 12]
 [14 16 18]]


In [61]:
# ## Subtracting one array from the other
print(np.subtract(arr1,arr2))


[[-6 -6 -6]
 [-6 -6 -6]]


In [62]:
## Multiplying the two arrays
print(np.multiply(arr1,arr2))


[[ 7 16 27]
 [40 55 72]]


In [63]:
## Dividing one array by the other
print(np.divide(arr1,arr2))


[[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


##### numpy.power()

This function treats elements in the first input array as base and returns it raised to the power of the corresponding element in the second input array.

In [64]:
a = np.array([10,100,1000])
print(np.power(a,2))


[    100   10000 1000000]


In [65]:
b = np.array([1,2,3])
print(np.power(a,b))


[        10      10000 1000000000]


##### numpy.mod()

Returns the remainder of division of the corresponding elements in the input array; the function numpy.remainder() also produces the same result

In [66]:
a = np.array([10,20,30]) 
b = np.array([3,5,7])

print("Applying mod() function: ", np.mod(a,b))
print("Applying remainder() function: ", np.remainder(a,b))



Applying mod() function:  [1 0 2]
Applying remainder() function:  [1 0 2]


##### Arithmetic Operations On Complex Numbers

##### numpy.real() 

Returns the real part of the complex data type argument

In [67]:
arr = np.array([-5.6j, 0.2j, 11. , 1+1j])
print("Array: ", arr)
print("Real part of the array elements: ", np.real(arr))


Array:  [-0.-5.6j  0.+0.2j 11.+0.j   1.+1.j ]
Real part of the array elements:  [-0.  0. 11.  1.]


##### numpy.imag() 

Returns the imaginary part of the complex data type argument

In [68]:
print("Imaginary part of the array elements: ", np.imag(arr))


Imaginary part of the array elements:  [-5.6  0.2  0.   1. ]


##### numpy.conj() 

Returns the complex conjugate, which is obtained by changing the sign of the imaginary part

In [69]:
print("Complex conjugate of the array elements: ", np.conjugate(arr))


Complex conjugate of the array elements:  [-0.+5.6j  0.-0.2j 11.-0.j   1.-1.j ]


#### NumPy Matrix Operations

- A matrix is a specialized 2-D array that retains its 2-D nature through operations
- Some popular matrix operations include additon, multiplication, transpose, determinant, rank and so on

In [2]:
## Addition of two matrices
import numpy as np
A = np.array([[2, 4], [5, -6]])
B = np.array([[9, -3], [3, 6]])

print(A)
print()
print(B)

[[ 2  4]
 [ 5 -6]]

[[ 9 -3]
 [ 3  6]]


In [71]:
C = np.add(A,B)                          
print(C)

[[11  1]
 [ 8  0]]


In [72]:
## Subtraction of one matrix from the other
D = np.subtract(A,B)
print(D)


[[ -7   7]
 [  2 -12]]


In [73]:
## Element-wise multiplication of matrices
E = np.multiply(A,B)
print(E)


[[ 18 -12]
 [ 15 -36]]


In [74]:
## Matrix multiplication 
F = np.dot(A,B)
print(F)


[[ 30  18]
 [ 27 -51]]


In [75]:
## Division of matrices
G = np.divide(A,B)
print(G)


[[ 0.22222222 -1.33333333]
 [ 1.66666667 -1.        ]]


In [76]:
## Transpose of a matrix

arr = np.array([[1, 1], [2, 1], [3, -3]])
print("Original array: \n", arr)
print("\nTranspose of the array: \n", arr.transpose())



Original array: 
 [[ 1  1]
 [ 2  1]
 [ 3 -3]]

Transpose of the array: 
 [[ 1  2  3]
 [ 1  1 -3]]


In [77]:
## Alternative method of transposition
print(arr.T)


[[ 1  2  3]
 [ 1  1 -3]]


In [78]:
## Square root of each matrix element

arr = np.array([[2,4,9],[121,100,8]])
print(np.sqrt(arr))


[[ 1.41421356  2.          3.        ]
 [11.         10.          2.82842712]]


In [79]:
## Rank of matrix - the dimensions of the vector space spanned (generated) by its columns or rows
## Determing rank using the matrix_rank() function which comes from the numpy linalg package

arr = np.array([[2,4,6],[10,11,12]])
print(np.linalg.matrix_rank(arr))



2


In [80]:
## Accessing matrix elements

A = np.array([[1, 4, 5, 12],[-5, 8, 9, 0],[-6, 7, 11, 19]])
print("Matrix: \n", A)
print("First element of first row: ", A[0][0])  
print("Third element of second row: ", A[1][2])
print("Last element of last row: ", A[-1][-1])



Matrix: 
 [[ 1  4  5 12]
 [-5  8  9  0]
 [-6  7 11 19]]
First element of first row:  1
Third element of second row:  9
Last element of last row:  19


In [81]:
## Accessing matrix rows
print("Third row of matrix A: ", A[2])


Third row of matrix A:  [-6  7 11 19]


In [82]:
## Accessing matrix columns
print("Last column of matrix A", A[:,-1])


Last column of matrix A [12  0 19]


#### NumPy Broadcasting

Broadcasting refers to the ability of NumPy to treat arrays of different shapes during arithmetic operations.

In [107]:
a = np.array([[10,10,10],[20,20,20],[30,30,30]]) 
b = np.array([1,2, 3])

In [108]:
a

array([[10, 10, 10],
       [20, 20, 20],
       [30, 30, 30]])

In [109]:
b

array([1, 2, 3])

In [110]:
a + b

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

### Class Exercise:

1. Create a ndarray of first five multiples of 6.
2. Convert the 1D array created in Q1 to 3D, and display the number of dimensions of the latter.
3. Create a 2D array where first 5 prime numbers occupy the 1st dimension & the first 5 composite numbers in the 2nd dimension.
4. From the array created in Q3, retrieve the last element from 2nd dimension.
5. Retrieve the 2nd, 3rd and 4th elements from both dimensions of the 2D array created in Q3.
6. Display the data type of the array created in Q1, and change it to float.
7. Create a 1D array of twelve zeros and reshape it to a 2D array of shape (3,4).
8. Flatten the 2D array that you created in the previous question back to 1D.
9. Consider an array [24,45,67,90,123,367]. Find the indexes where the values are even.
10. Create two arrays, one with first 5 odd numbers and the other with first 5 even numbers. Then concatenate both the arrays along columns.
11. Subtract the even number array from the odd number array created in Q10.
12. Create two matrices of the squares and cubes of first 4 natural numbers, and perform matrix multiplication. Also, obtain the transpose of the matrix resulting from the multiplication.

In [89]:
## 1. Create a ndarray of first five multiples of 6

import numpy as np
arr = np.array([6,12,18,24,30])
print(arr)

[ 6 12 18 24 30]


In [90]:
## 2. Convert the 1D array created in Q1 to 3D, and display the number of dimensions of the latter

arr_1 = np.array([[[6,12,18,24,30]]])
print("Array: ", arr_1)
print("Dimensions of array: ", arr_1.ndim)

Array:  [[[ 6 12 18 24 30]]]
Dimensions of array:  3


In [91]:
## Alternative solution to Q2

arr_1 = np.array([6,12,18,24,30], ndmin=3)
print("Array: ", arr_1)
print("Dimensions of array: ", arr_1.ndim)

Array:  [[[ 6 12 18 24 30]]]
Dimensions of array:  3


In [92]:
## 3. Create a 2D array where first 5 prime numbers occupy the 1st dimension and the first 5 composite numbers in the 2nd dimension

arr_2 = np.array([[2,3,5,7,11],[4,6,8,9,10]])
print(arr_2)

[[ 2  3  5  7 11]
 [ 4  6  8  9 10]]


In [93]:
## 4. From the array created in Q3, retrieve the last element from 2nd dimension

print(arr_2[1,-1])

10


In [94]:
## 5. Retrieve the 2nd, 3rd and 4th elements from both dimensions of the 2D array created in Q3

print(arr_2[0:2, 1:4])

[[3 5 7]
 [6 8 9]]


In [95]:
## 6. Display the data type of the array created in Q1, and change it to float

arr = np.array([6,12,18,24,30])
print(arr.dtype)

int32


In [96]:
new_arr = arr.astype(float)
print(new_arr)

[ 6. 12. 18. 24. 30.]


In [97]:
## 7. Create a 1D array of twelve zeros and reshape it to a 2D array of shape (3,4)

arr = np.zeros(12)
print("1D array of zeros: ", arr)
new_arr = arr.reshape(3,4)
print("2D array of zeros: \n", new_arr)

1D array of zeros:  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
2D array of zeros: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [98]:
## 8. Flatten the 2D array that you created in the previous question back to 1D

arr_1d = new_arr.reshape(-1)
print(arr_1d)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [99]:
## 9. Consider an array [24,45,67,90,123,367]. Find the indexes where the values are even

arr = np.array([24,45,67,90,123,367])
a = np.where(arr%2 == 0)
print(a)

(array([0, 3], dtype=int64),)


In [100]:
## 10. Create two arrays, one with first 5 odd numbers and the other with first 5 even numbers. 
##     Then concatenate both the arrays along columns

arr1 = np.array([1,3,5,7,9])
arr2 = np.array([2,4,6,8,10])
arr3 = np.vstack((arr1,arr2))
print(arr3)

[[ 1  3  5  7  9]
 [ 2  4  6  8 10]]


In [101]:
## 11. Subtract the even number array from the odd number array created in Q10

arr1 = np.array([1,3,5,7,9])
arr2 = np.array([2,4,6,8,10])
arr3 = np.subtract(arr1,arr2)
print(arr3)

[-1 -1 -1 -1 -1]


In [102]:
## 12. Create two matrices of the squares and cubes of first 4 natural numbers, and perform matrix multiplication. 
##     Also, obtain the transpose of the matrix resulting from the multiplication

arr1 = np.array([[1,4],[9,16]])
arr2 = np.array([[1,8],[27,64]])
arr3 = np.dot(arr1,arr2)
print("Matrix multiplication: \n", arr3)
print("Transpose: \n", arr3.T)                                    # alternatively, arr3.transpose()

Matrix multiplication: 
 [[ 109  264]
 [ 441 1096]]
Transpose: 
 [[ 109  441]
 [ 264 1096]]


#### end of the notebook