In [ ]:
# 1. Find the largest value in the following array: arr1 = np.array([24, 0,  16, 75, 4, 31, 99])
# 2. Find the 3 largest values in the following array: arr2 = np.array([24, 0,  16, 75, 4, 31, 99])
# 3. Filter out only the float-type elements from the following array: arr3 = np.array([1, 1.2, 2, 5.6, 7.0, 42.0])
# 4. Compute the mean of the following array while ignoring NaN: arr4 = np.array([[120, 5, 34], [37, 3, np.nan]])   
# 5. Write a function that calculates the sum of all columns of a 2-D array
# 6. Sort the following matrix: arr6 = np.matrix('[44, 12, 19; 22, 3, 1; 4, 65, 8]')
# 7. Remove the nans from the following array. Hint: use bitwise operations
#                 arr7 = np.array([[101, 2.5, np.nan],
#                                 [8.7, 52, np.nan]])
# 8. Find the indices of all 0s in the array. Hint: use np.where()
#                 arr8 = np.array([1, 0, 4, 0, 3, 1, 0, 5, 5, 0, 6, 7, 0, 5, 9, 8])
# 9. Add np.array([[1], [2], [3]]) as a new column in the following matrix:
#                 arr9 = np.array([[14, 22, 3], [65, 1, 6], [79, 0, 110]])
# 10. Create the following 3-D array:
#            [[[ 0  1  2  3]
#              [ 4  5  6  7]
#              [ 8  9 10 11]
#              [12 13 14 15]]

#             [[16 17 18 19]
#              [20 21 22 23]
#             [24 25 26 27]
#             [28 29 30 31]]

#            [[32 33 34 35]
#             [36 37 38 39]
#            [40 41 42 43]
#            [44 45 46 47]]]
# and obtain its diagonal elements in a 2-D array:
#           [[ 0  5 10 15]
#            [16 21 26 31]
#            [32 37 42 47]]