### Maximum and Minimum of array

In [1]:
import numpy as np
arr= np.array([[12,25,38],[99,61,35],[76,32,12]])  
print(arr)

[[12 25 38]
 [99 61 35]
 [76 32 12]]


In [2]:
# minimun
np.amin(arr)

12

In [3]:
# maximum
np.amax(arr)

99

### Mean, Median, Standard Deviation and Variance

We will learn about these statistical functions in more detail later on

In [4]:
arr2 = np.array([3,4,5]) 
print(arr2)

[3 4 5]


In [5]:
# mean
np.mean(arr2)

4.0

In [6]:
# median
np.median(arr2)

4.0

standard deviation is a measure of the amount of variation or dispersion of a set of values

In [7]:
# standard deviation
np.std(arr2)

0.816496580927726

variance is the squared deviation from the mean

In [8]:
# variance
np.var(arr2)

0.6666666666666666

### NumPy Average Function

The multi-dimensional arrays and the weighted average are calculated via the NumPy np.average() function. The component is multiplied by its weight, which is given individually, to create the weighted average. If weights are not provided, mean is produced instead.

In [9]:
arr2

array([3, 4, 5])

In [10]:
print(np.average(arr2))

4.0


In [11]:
# with weight gives weighted average
wt = np.array([6,2,5])
print(np.average(arr2, weights=wt))

3.923076923076923


### NumPy Percentile Function

- input: it is the input array.
- q: it is the percentile which it calculates of the array elements between 0-100.
- axis: it specifies the axis along which calculation is performed.

In [12]:
print(arr2)
print(np.percentile(arr2,10,0))

[3 4 5]
3.2


### NumPy Peak-to-Peak Function

To determine the range (max-min) of values along an axis

In [13]:
arr3 = np.array([[2,10,20],[6,10,60]])  
arr3

array([[ 2, 10, 20],
       [ 6, 10, 60]])

In [14]:
# along axis 0
np.ptp(arr3,0)

array([ 4,  0, 40])

In [15]:
# along axis 1
np.ptp(arr3,1)

array([18, 54])

### Class Exercise:

- Create a 2-D array and compute its median along the horizontal axis, vertical axis, and overall median
- Calculate the 25th and 75th percentile of the array = [1, 3, 4, 7, 12, 15, 2, 19, 8, 19]
- Create a 2D array where first 5 even numbers occupy the 1st dimension & the first 5 odd numbers in the 2nd dimension. Calculate its range along axis=1

In [16]:
# create a 2D array
array1 = np.array([[2, 3, 96], 
                   [3, 8, 18], 
                   [15, 16, 11]])

# horizontal axis 
result1 = np.median(array1, axis=1)
print(result1)

# vertical axis
result2 = np.median(array1, axis=0)
print(result2)

# compute median of entire array
result3 = np.median(array1)
print(result3)

[ 3.  8. 15.]
[ 3.  8. 18.]
11.0


In [17]:
array2 = np.array([1, 3, 4, 7, 12, 15, 2, 19, 8, 19])

# compute the 25th percentile of the array
result1 = np.percentile(array2, 25)
print("25th percentile:",result1)

# compute the 75th percentile of the array
result2 = np.percentile(array2, 75)
print("75th percentile:",result2)

25th percentile: 3.25
75th percentile: 14.25


In [18]:
array3 = np.array([[2,4,6,8,10],[1,3,5,7,9]])
np.ptp(array3, 1)

array([8, 8])

#### end of the notebook.